## Modified commands
alias xo='xdg-open'

## Privileged access
if (( UID != 0 )); then
    alias reboot='sudo systemctl reboot'
    alias poweroff='sudo systemctl poweroff'
    alias update='sudo pacman -Syu'
fi

## Safety features
alias cls=' echo -ne "\033c"'       # clear screen for real (it does not work in Terminology)